### ISSUE TITLE
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function html

### ISSUE THREAD

**Issue by CRtEurope** [JohnDoh/Roundcube-Plugin-SpamAssassin-User-Prefs-SQL#38]
I am using the latest roundcube master branch version and I am getting the following errors in the log files.

sauserprefs - latest master branch version
roundcube - latest master branch version
PHP 7.1.2

![error](https://cloud.githubusercontent.com/assets/16518395/26490864/619d92ea-420d-11e7-8cba-ca87824d87ac.jpg)

```
[26-May-2017 12:02:14 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function html::span(), 1 passed in plugins/sauserprefs/sauserprefs.php on line 681 and exactly 2 expected in program/lib/Roundcube/html.php:197
Stack trace:
#0 plugins/sauserprefs/sauserprefs.php(681): html::span(Array)
#1 plugins/sauserprefs/sauserprefs.php(218): sauserprefs->_prefs_block('tests', Array)
#2 program/include/rcmail_output_html.php(1143): sauserprefs->gen_form(Array)
#3 [internal function]: rcmail_output_html->xml_command(Array)
#4 program/include/rcmail_output_html.php(1014): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#5 program/include/rcmail_output_html.php(635): rcmail_output_html->parse_xml('<ro in program/lib/Roundcube/html.php on line 197
[26-May-2017 12:02:15 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function html::span(), 1 passed in plugins/sauserprefs/sauserprefs.php on line 791 and exactly 2 expected in program/lib/Roundcube/html.php:197
```

**Comment by JohnDoh** [comment]
fixed. thanks for pointing it out
